### ISSUE TITLE
[Feature Request] Support to merge duplicate code

### ISSUE THREAD

**Issue by fengyuanchen** [tbremer/postcss-atrule-bem#6]
Current: 

```css
@block btn {
  color: #333;

  &:disabled {
    color: #ccc;
  }

  @modifier disabled {
    color: #ccc;
  }
}
```

Feature:

```css
@block btn {
  color: #333;

  &:disabled,
  @modifier disabled {
    color: #ccc;
  }
}
```

**Comment by tbremer** [comment]
I don't plan to support this, there are two plugins [postcss-merge-rules](https://github.com/ben-eb/postcss-merge-rules) and [postcss-merge-selectors](https://github.com/georgeadamson/postcss-merge-selectors) that enable this type of code tidying.

Those plugins combined with `postcsss-nested` would let this work out.

**Comment by fengyuanchen** [comment]
**Not** work with the following config (`postcss.config.js`):

```js
module.exports = {
  plugins: {
    'postcss-atrule-bem': {},
    'postcss-merge-rules': {}, // or 'postcss-merge-selectors': {},
    'postcss-nested': {},
  },
};
```

Or:

```js
module.exports = {
  plugins: {
    'postcss-atrule-bem': {},
    'postcss-nested': {},
    'postcss-merge-rules': {},  // or 'postcss-merge-selectors': {},
  },
};
```

**Comment by fengyuanchen** [comment]
Only works after removed at-rule as this: 

```css
@block btn {
  color: #333;

  &:disabled,
  &[disabled] {
    color: #ccc;
  }
}
```
