### ISSUE TITLE
[Feature Request] Support & + & in @element or @modifier

### ISSUE THREAD

**Issue by fengyuanchen** [tbremer/postcss-atrule-bem#7]
Current: 

```css
@block list {
  margin: 0;

  @element item {
    padding: .5rem 1rem;

    & + .list__item {
      margin-left: .5rem;
    }
  }
}
```

Feature:

```css
@block list {
  margin: 0;

  @element item {
    padding: .5rem 1rem;
    
    & + & {
      margin-left: .5rem;
    }
  }
}
```
